import type { Metadata } from "next";
import "./globals.css";
import { sarabun } from "./fonts";

export const metadata: Metadata = {
  title: "Advanced Next.js 15+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.className}`}>
        {children}
      </body>
    </html>
  );
}
